### PR TITLE
revamped the UI (#2)

### PR DESCRIPTION
**Pull request by anubhav1206**
revamped the UI with better colors, gardients, animations and transitions

### CODE REVIEW

**Comment by avinashji1302** [comment]
> revamped the UI with better colors, gardients, animations and transitions

## Looks good...just fix this 

Screenshot (45)

**Comment by avinashji1302** [comment]
> revamped the UI with better colors, gardients, animations and transitions

## Looks good...just fix this 

Screenshot (45)

**Comment by anubhav1206** [comment]
done

> > revamped the UI with better colors, gardients, animations and transitions
> 
> ## Looks good...just fix this
> Screenshot (45)

done, please check.

**Comment by avinashji1302** [comment]
> done
> 
> > > revamped the UI with better colors, gardients, animations and transitions
> > 
> > 
> > ## Looks good...just fix this
> > Screenshot (45)
> 
> done, please check.

##  cover the card with border and will merge it

Screenshot (46)

**Comment by anmol111pal** [comment]
Hey @avinashji1302 , may i review the changes ?
Please assign me the task to review these changes.

**Comment by anmol111pal** [comment]
Hey, @anubhav1206 , according to me there's a lot of cnontrast in the UI. Do check this.
There is unnecessary gradient in the input fields.
@avinashji1302

**Comment by anubhav1206** [comment]
> Hey, @anubhav1206 , according to me there's a lot of cnontrast in the UI. Do check this. There is unnecessary gradient in the input fields. @avinashji1302

I'll change the input field text color to something nicer and use a different color for the background.

**Comment by anubhav1206** [comment]
image
How does this look?

**Comment by anmol111pal** [comment]
Dont put a dark theme @anubhav1206

**Comment by anubhav1206** [comment]
> > done
> > > > revamped the UI with better colors, gardients, animations and transitions
> > > 
> > > 
> > > ## Looks good...just fix this
> > > Screenshot (45)
> > 
> > 
> > done, please check.
> 
> ## cover the card with border and will merge it
> Screenshot (46)

added a border around the weather card and fixed the contrast, please check

**Comment by anmol111pal** [comment]
Resolve the merge conflicts @anubhav1206 .
 Overall the design is good 👍

**Comment by anubhav1206** [comment]
> Resolve the merge conflicts @anubhav1206 . Overall the design is good 👍

how do i reslove them?

**Comment by anmol111pal** [comment]
@avinashji1302 please look into this.

**Comment by avinashji1302** [comment]
##  @anubhav1206 recently some other pull request got merged thats why This conflict is rising

### Stpes to solve it 
git checkout master
git pull
git checkout <branch>
git merge master
[ ... resolve any conflicts ... ]
git add [files that were conflicted]
git commit
git push

## follow the link to understand better or you can simply google it
[https://www.simplilearn.com/tutorials/git-tutorial/merge-conflicts-in-git](url)

**Comment by avinashji1302** [comment]
> ## @anubhav1206 recently some other pull request got merged thats why This conflict is rising
> ### Stpes to solve it

 git checkout master 
git pull git checkout 
git merge master [ ... resolve any conflicts ... ]
 git add [files that were conflicted] 
git commit 
git push


> ## follow the link to understand better or you can simply google it
>##  [https://www.simplilearn.com/tutorials/git-tutorial/merge-conflicts-in-git](url)



##  Please  Do not Change the poistion of div element just change the color (See 'forecast cloud and time position in your PR"

# See the latest photo
Screenshot (47)

**Comment by DavidKozdra** [comment]
what is the delay on this PR?

**Comment by anubhav1206** [comment]
> > ## @anubhav1206 recently some other pull request got merged thats why This conflict is rising
> > ### Stpes to solve it
> 
> git checkout master git pull git checkout git merge master [ ... resolve any conflicts ... ] git add [files that were conflicted] git commit git push
> 
> > ## follow the link to understand better or you can simply google it
> > ## [https://www.simplilearn.com/tutorials/git-tutorial/merge-conflicts-in-git](url)
> 
> ## Please Do not Change the poistion of div element just change the color (See 'forecast cloud and time position in your PR"
> # See the latest photo
> Screenshot (47)

will look into this

**Comment by anubhav1206** [comment]
made the changes, kindly check.

**Comment by avinashji1302** [comment]
> made the changes, kindly check.

Everything is good.... please resolve this conflict.... Please follow the above steps already mentioned

**Comment by anubhav1206** [comment]
> > made the changes, kindly check.
> 
> Everything is good.... please resolve this conflict.... Please follow the above steps already mentioned

okay

**Comment by anubhav1206** [comment]
> > made the changes, kindly check.
> 
> Everything is good.... please resolve this conflict.... Please follow the above steps already mentioned

I cant seem to find any merge conflicts,. 
image

**Comment by avinashji1302** [comment]
> > > made the changes, kindly check.
> > 
> > 
> > Everything is good.... please resolve this conflict.... Please follow the above steps already mentioned
> 
> I cant seem to find any merge conflicts,. image

Fork again this repository... copy paste your changes in recent repository and push those changes....I  guess you are working on your old repository that you initially forked....

**Comment by anubhav1206** [comment]
> > > > made the changes, kindly check.
> > > 
> > > 
> > > Everything is good.... please resolve this conflict.... Please follow the above steps already mentioned
> > 
> > 
> > I cant seem to find any merge conflicts,. image
> 
> Fork again this repository... copy paste your changes in recent repository and push those changes....I guess you are working on your old repository that you initially forked....

okay

**Comment by anubhav1206** [comment]
done kindly check

**Pull request closed without merging**
